redis:
  image: redis

db:
  image: postgres:9.4

result:
  image: result-app
  ports:
    - 5001:80
  links:
    - db

vote:
  image: voting-app
  ports:
    - 5000:80
  links:
    - redis

worker:
  image: worker-app
  links:
    - db
    - redis